### ISSUE TITLE
[ System request ] - SFRPG ( Starfinder )

### ISSUE THREAD

**Issue by Nachtrose** [otigon/automated-jb2a-animations#67] opened 2021-05-24 07:17 UTC
The title sums it up pretty much. Check and include ( if possible ) the support for Starfinder - SFRPG.

Thanks.

**Comment by otigon** [comment] 2021-06-07 20:15
In Starfinder, are attack/damage always rolled from the Chat Card buttons?

**Comment by TimToxopeus** [comment] 2021-06-07 20:54
Nachtrose asked me to comment on this question, as I'm one of the system developers. :-)

No, you can also roll attack/damage from the actor sheets.

If it helps, with the next release of the Starfinder system there will be hooks made available for when an attack or damage is rolled successfully, along with whether or not it was a crit.

Unless anything changes before release, the format of these hooks will work as such:
Hooks.on("attackRolled", ({actor, item, roll, formula, rollMetadata}) => { });
Hooks.on("damageRolled", ({actor, item, roll, isCritical, formula, rollMetadata}) => { });

Note that item can be null for certain actors (Hazards).
Roll metadata is usually null, but can be used for passing through information when used with macros.

**Comment by otigon** [comment] 2021-06-07 21:10
@TimToxopeus Thanks for the info! I was searching around on the Starfinder System and those hooks would definitely make it easier to add support. I think the way it is right now, any item information is lost in the Chat Card when attack/damage is rolled.

The other issue I'm running into is that the "renderItemSheet" hook is called twice for some items. I can't seem to pin down why it happens with some, and not others. For example using items in the supplied "Equipment" Compendium:
Anchor Pistol: Emergent: Renders only Once
Anchor Pistol: Flux: Renders Twice
Dirge Piston: Anharmonic: Renders Twice

By "Renders Twice" I mean to say that the renderItemSheet hook is called twice on opening, and anytime you update the item.

Do you know if this is intended behavior for some items versus others?

**Comment by TimToxopeus** [comment] 2021-06-07 21:13
That is probably caused by a particularly adventurous attempt of automating some fields without actually automating it properly. It loads up, does some calculations, which then forces a refresh of the sheet. This is a consequence of the async rolls change from FoundryVTT 0.8.x, it can no longer be computed immediately. :(

**Comment by otigon** [comment] 2021-06-07 21:14
Pesky 0.8 changes. I'll find a work-around for that

**Comment by fatigues65** [comment] 2021-06-09 05:32
> The title sums it up pretty much. Check and include ( if possible ) the support for Starfinder - SFRPG.
> 
> Thanks.

The degree to which adding support for animated "pew-pew" to Starfinder RPG in Foundry VTT will be used and appreciated is difficult to overstate. Yes, 5e and PF2 have ranged attack systems, too, obviously. But neither of those games is like Starfinder in the sense that "pew-pew" ranged  combat is the heart of all combat in Sci Fi game like Starfinder. Melee is the exception, not the rule in Starfinder.  In Starfinder, we are all about shooting things and throwing grenades at them!

**Comment by otigon** [comment] 2021-06-09 13:04
That shouldn't be a problem. I just need to figure out a work-around for the duel rendering on the item sheets. As a last resort, support may be delayed a little bit while I move the Animation Tab from the Item Sheet to a Form Application style

**Comment by fatigues65** [comment] 2021-06-09 13:20
> No, you can also roll attack/damage from the actor sheets.

And for a lot of people who use Foundry VTT -- from the module Token Action Hud - though that is a shortcut to the sheet if I understand how the module works.

**Comment by otigon** [comment] 2021-06-28 13:57
Following up on this, I'm reworking how the Tabbed A-A settings function, and will be moving it to a Form Application type on the Item Sheet title-bar. This should allow for integration of SFRPG even with the duplicate renderItemSheet hooks firing.

**Comment by fatigues65** [comment] 2021-06-28 17:14
Fantastic! We are talking about this now in the #starfinder Discord channel.  There is excitement :)

**Comment by otigon** [comment] 2021-07-04 20:40
Starfinder support is live as of release 0.4.00. I'll close this issue for now, but feel free to ping me on Discord or log issues here for any bugs you find, or specific scenarios I overlooked

**Closed by otigon** 2021-07-04 20:40 UTC
