### ISSUE TITLE
JB2A free animations launching from the wrong token.

### ISSUE THREAD

**Issue by LethalStinky** [otigon/automated-jb2a-animations#466] opened 2022-08-05 04:45 UTC
I'm running the free version as a trial to see if it's something that I want to pay for with Patreon, and I'm also using Automated Animations, but for some reason when I select the target of any attack and execute the attack, the animation fires from the wrong token than the one that is actually attacking. Any ideas how to fix this, because this is solidly the coolest thing to every show up on my table but I would really rather the module work properly.

**Comment by otigon** [comment] 2022-08-05 13:03
Hey there, what system are you using this in, and are you on the latest version of Automated Animations? (version 3.2.97).

Also, does this occur when attacking from a linked token (player) or npc, or both?

**Comment by otigon** [comment] 2022-08-05 13:42
Oh and just FYI, this is a separate module from JB2A. They are the animators and I'm just the sucker who made a module to play them lol. The JB2A Discord is a great place to get more detailed info on stuff as well: https://discord.gg/DMtXmtMg

**Comment by LethalStinky** [comment] 2022-08-06 09:08
I’m running it on 5E and when I make the attack I have the token I want the
attack to come from selected and the target of the attack targeted. When I
hit attack, it launches the attack from someone else completely lol.
🤦‍♂️Also, would it be better for me to contact support through the discord
or should I keep going through this email thread?

PS thank you for getting back to me so quickly. I genuinely figured it
would take like a week or two lol. You kick ass.

**Comment by otigon** [comment] 2022-08-06 12:54
Hey thanks for the info. Let me do some testing on my end first and see if I can replicate the issue.

I do have a troubleshooting channel on the JB2A Discord for A-A if you want to pop in there as well. I think we are in different time zones so there's probably some lag in communication time

**Comment by otigon** [comment] 2022-08-06 14:03
Hey so I'm unable to replicate any issues with the animations playing from the correct token. I tested with Core 5e, Token Action Hud, and Midi-QOL.

Sometimes if you have multiple of the same token on the canvas, if you are opening the sheet from the Actors Directory (on Right Hand Panel), you need to have the token selected that you are attacking from, otherwise it will grab the first token from that Actor on the canvas and initiate the attack from there. Otherwise if you are opening the sheet directly from the token it should work as normal without having to select the token.

On important thing to check:
1. Make sure you are on the latest Automated Animations version 3.2.97.

There was a bug in a previous version that was causing something similar to the issue you are seeing.

Outside of those steps, you may have another module interfering. This would depend most likely on modules you have active that affect rolling. If you are using Better Rolls, this could be the cause. 

Let me know

**Comment by otigon** [comment] 2022-08-29 20:57
Forgot to close this. This was fixed in the latest A-A for non-linked tokens. Linked token issue still occurs, but I have a fix in the Verison 4 release (date TBD)

**Closed by otigon** 2022-08-29 20:57 UTC
