### ISSUE TITLE
Add Audio option in the Automatic Recognition Settings

### ISSUE THREAD

**Issue by remiverdel** [otigon/automated-jb2a-animations#294] opened 2021-12-06 15:36 UTC
Hi,

Really love your module and the straightforwardness of it!

I just thought that maybe Audio settings could be added inside the Automatic Recognition Settings instead of being only a per item settings. For exemple, 8 of my players have Daggers, so I needed to go inside there inventory and set the appropriate audio settings 8 times for a single item. Maybe if it was possible to implement the audio function inside the Automatic Recognition Settings, it could speed up a lot of the audio work as it does for animations!

Tell me what you think,

Cheers,

Rémi

**Comment by otigon** [comment] 2021-12-06 15:51
I'm in the process of reworking all the audio in the module. It will have sound setting in the automatic recognition menu

**Comment by SalieriC** [comment] 2021-12-19 10:23
Duplicate of #293.

**Comment by otigon** [comment] 2021-12-30 00:09
Active in version 1.0, closing issue

**Closed by otigon** 2021-12-30 00:09 UTC
