### ISSUE TITLE
Animations not triggering off of "Feat" Chat cards when Auto recognition is used

### ISSUE THREAD

**Issue by Michael-B-23** [otigon/automated-jb2a-animations#417] opened 2022-05-29 16:43 UTC
System PF2E (3.10.4.11747)
Foundry Version 9 (build 269)
Automated Animations version 3.2.0

Seems like animations are not triggering off of chat cards posted from the "feats" section IF its autorec enabled. 

If its NOT auto rec, and just configured in the item, it works fine. Or if AutoRec is configured, but custom animation is checked, it also works.

Still fails if AutoRec configured but Override is checked.

No console error messages.

**Comment by otigon** [comment] 2022-06-05 14:18
It looks like when I added support for Active Effects types in PF2e, I grouped "Feats" in with this. It functions correctly from the Active Effects tabs in the Autorec menu.

Is this something that maybe should be grouped into normal animations? The only difference being that when it is treated as an Active Effect type, "Templates" "Melee" and "Ranged" animations are not available.

**Comment by Michael-B-23** [comment] 2022-06-05 15:01
I personally believe it should be grouped in with normal animations. Feats in PF2E can do a million things but do not always leave a "condition" or "effect" which is where I think active affects shines. 

Plus, it seems there are a few other issues. Hunt Prey, as example. I use the "Hunters Mark" Preset. That doesn't seem available from the active effects menu. 

Feel free to gather other opinions, obviously, but I just see Feats as a lot closer to Items or Spells than active effects. Plus, any feat that provides an ongoing effect, is often added to the token via  rule element, so you could still code the animation via active affects, triggered off the rule element name if you wanted to do it that way.

**Comment by otigon** [comment] 2022-06-09 02:30
So there can only be one way to go on this with feats. I either treat them solely as Active Effects, in which case it would only apply the animation when the Effect is applied, or I treat Feats as items and only activate on sending the item to chat.

I can't find anywhere in the PF2e Item data structure where it specifies which Feats have Effects and which don't 

You say they should be Active Effects, and #418  says normal items. I don't see a feasible way to treat it as both.

I'll chew on it a bit

**Comment by otigon** [comment] 2022-06-10 00:06
Reposting from #418 

I think I found in the data where it shows whether a Feat has an "effect" associated it under item.data.data.actions.value. Where it is null if it has no effect, and some value if it does. I should be able to use this to exit out of the workflow when posting a Feat to Chat if it has an effect attached to it, otherwise play any associated animation

Edit Looking closer, it seems like the "feats" are divided into "Passive" "Action" "Reaction" etc. Passive Feats do not have any Active type Effects tied to them, while the others do. I can use this to fix these as noted above. This should be a good middle ground, since if an Effect has an AE tied to it, the assumption would be that if sent to chat you would be applying that effect.

**Comment by Ghilteras** [comment] 2022-07-22 17:39
Just tried an Ape Fist (Rule Element that creates a strike on Animal Instinct Barbarian) and the animation still does not play even with the new release which includes the PR above

**Comment by Ghilteras** [comment] 2022-08-22 22:11
Looks like this can be closed as a dupe of https://github.com/otigon/automated-jb2a-animations/issues/436 and potentially https://github.com/otigon/automated-jb2a-animations/issues/436

**Comment by otigon** [comment] 2022-10-25 00:48
With the newer releases for A-A version 4+, and V10 PF2e, these should all be working as intended now. Strikes granted by these features will only play on Attack Rolls however. When rolling damage for those, they don't reference to anything I can grab in A-A. The PF2e devs are aware of this and an issue has been logged on the PF2e site. This will most likely be a while before it's fixed because it is rolled into their full "Damage" workflow overhaul

**Closed by otigon** 2022-10-25 00:48 UTC
Labels: bug
