### ISSUE TITLE
Automatic Recognition doesn't detect PF2e runes (outside of +1,2,etc) on weapons

### ISSUE THREAD

**Issue by jdwpom** [otigon/automated-jb2a-animations#217] opened 2021-09-12 05:06 UTC
For a couple of specific examples from a campaign, the 'Greatsword' entry in the automatic matching won't match with '+1 Striking Fearsome Greatsword'. If I add in a 'Striking Fearsome Greatsword' entry, this works as intended, but takes away from the automation a little.

**Comment by otigon** [comment] 2021-09-12 11:54
It is impossible to account for everything, and I have no clue about what a rune system is for PF2E. The "automation" is the animations, bit name checking sorry

**Comment by otigon** [comment] 2021-09-12 13:46
Would it be more beneficial in a system like PF2E to include certain keywords to ignore as part of the automatic menus? Currently I'm using regex to erase the +1, +2 etc. If it would be better for a specific system I can input a system specific method for it O-ring certain words, in this case the runes I. pF2e

**Comment by mercuriun** [comment] 2021-09-12 16:16
Could you use regex to FIND the weapon instead of ignore the runes?
If GREATSWORD is found, it's resolve the problem of any rune and modifier...
A option to "including" or not can be put to, to save problems in some system/cases...
it's possible?

**Comment by otigon** [comment] 2021-09-12 16:26
Is there any documentation available for this Rune system that I can read on?

**Comment by mercuriun** [comment] 2021-09-12 17:09
I really don't know, but it's easy for me to get a full list of all the runes.
The weapon name have the name of the rune on it. like in the exemple:

 '+2 Greater Striking Fearsome Greatsword'
the runes are:
Weapon Potency (+2)
Striking (Greater)
Fearsome

Could it help??

**Comment by jdwpom** [comment] 2021-09-12 20:13
PF2e's "Potency" (+1 through +4) are the same as everything else, so at least that bit's easy. The number of your 'potency' rune is also the number of possible "Property" runes you can put on the weapon. It doesn't look like Foundry's Pf2e system lets you change that in a fashion that changes the item name.

The "Striking" runes have 3 options - "Striking", "Greater Striking", and "Major Striking", as listed here - https://2e.aonprd.com/Equipment.aspx?ID=280 - The website styles them as "Striking (Greater/Major), but this is flipped in weapon naming in Foundry.

This should be a complete list of the "Property" Runes. The 'Greater' items are also styled as 'Greater $1' in the Foundry weapon name, so "Thundering (Greater)" becomes "Greater Thundering"
https://2e.aonprd.com/Equipment.aspx?Category=23&Subcategory=27

Your weapon can also be made of various materials, listed here - 
https://2e.aonprd.com/Equipment.aspx?Category=37&Subcategory=38
The grade portion in brackets does not apply to the weapon in Foundry, nor does the word 'Weapon', so "Adamantine (Standard Grade)", just becomes "Adamantine" in Foundry.

The order these are applied to weapon names in Foundry is:
Potency
Striking
Property (potentially repeated)
Material
Weapon Base

So for the sake of some examples with most hiccups I can see (these aren't necessarily likely combinations, just possible ones)- 

(Potency) (Striking) (Property) (Material) (Weapon Base)
+1 Greater Striking Greater Thundering Adamantine Greatsword

(Potency) (Striking) (Property) (Property) (Material) (Weapon Base)
+2 Major Striking Greater Thundering Greater Brilliant Adamantine Greatsword

(Potency) (Striking) (Property) (Property) (Property) (Property) (Material) (Weapon Base)
+4 Striking Greater Thundering Dancing Fearsome Greater Brilliant Darkwood Greatsword

This is getting outside of my area of knowing things, but some specific items are +1 by default, so they don't have that in their name. The only example I know of is "Handwraps of Mighty Blows", which, no matter what runes are added, seem to always just be called "Handwraps of Mighty Blows". 

I *think* that covers everything that Foundry's PF2e system does with weapon naming. I've fiddled about with most of the options and this seems to be the only things affecting the default naming system, but a better GM than me might know more.

**Comment by otigon** [comment] 2021-09-13 02:06
There is a PR in que to change some of the auto recognition to an includes method. I'll give that a test first tomorrow to see how it plays with this

**Comment by otigon** [comment] 2021-09-13 03:01
I just pushed 0.6.05 thanks to the PR from @DarkDinDon that switches this to an includes() method with more precision than I was able to get. Greatsword in the automatic menu should now capture all items containing "greatsword" in the name. And if you want a special animation specifically for the +1 Greater Striking Greatsword you can still list that in the automatic menu to capture it.

I'll leave this open for another day or two, so please let me know if you hit any snags with it

**Comment by otigon** [comment] 2021-09-13 04:27
With this PR, the regex will still eliminate +1, +2, +3, +4 from any names before doing checks. But, simply using "greatsword" in the name field on the auto-rec menu should capture all variations of those.... crazy combinations lol

**Comment by mercuriun** [comment] 2021-09-13 18:56
Thank you very much!

**Comment by otigon** [comment] 2021-09-15 16:09
Going to close this issue out. Please let me know if everything is working as intended now for capturing the rune items

**Closed by otigon** 2021-09-15 16:09 UTC
