### ISSUE TITLE
[Bug] Animations are triggered when procedurally creating disabled Active Effects

### ISSUE THREAD

**Issue by paulohdsc** [otigon/automated-jb2a-animations#419] opened 2022-05-30 12:31 UTC
I noticed that A-A triggers the animations if you procedurally create an inactive Active Effect ("disabled": true).

This is especially relevant because of a recent DAE update. As stated in the version 0.10.13 changelog:

> _DAE will treat any effect whose label matches a condition (as in condition immunity) as a condition and mark the effect disabled if the actor has immunity to that condition (i.e. unavailable)._

In these cases, DAE will create a disabled Active Effect and A-A will incorrectly trigger the animation.

**Comment by otigon** [comment] 2022-06-05 14:30
Can you provide an example of how to replicate this?

**Comment by paulohdsc** [comment] 2022-06-06 00:27
DnD 5e with A-A, Convenient Effects and DAE activated:

1. Create a new actor and give him immunity to any condition (e.g. Blinded)
2. Choose one option:
2.1. Use Convenient Effects to apply the Blinded Active Effect OR
2.2. Use a macro to create the Blinded Active Effect via `actor.createEmbeddedDocuments()`
3. Because of the immunity, DAE creates an inactive Active Effect
4. See that, even though the effect is inactive, A-A applies the AE animation

**Comment by otigon** [comment] 2022-06-06 00:29
Thanks, that should help me reproduce it. I was attempting to apply it through an Item use (Fear Spell in this case) and Midi/DAE wasn't applying the Frightened condition at all

**Comment by otigon** [comment] 2022-06-19 03:41
fix is in place on version 3.2.2

**Comment by otigon** [comment] 2022-06-19 03:46
reopening due to release issues

**Comment by otigon** [comment] 2022-06-19 05:17
released on 3.2.8

**Closed by otigon** 2022-06-19 05:17 UTC
