### ISSUE TITLE
Animations stop working after Compendium and permissions interaction

### ISSUE THREAD

**Issue by Suracha-123** [otigon/automated-jb2a-animations#331] opened 2022-01-18 20:54 UTC
Steps:
1. Trusted Player was not allowed to modify spell in Compendium - Compendium is not locked. Note that this is almost certainly not a Automated Animations issue, as they could also not change the spell's icon.
2. Installed Arbron's Compendium Tools to allow the player to edit the Compendium's items. Did not work. Likely due to conflict between non-AA modules, or our flimsy network setup.
3. Gave player Assistant GM permission. Compendium and AA tab flickered briefly, but did not update with the changes the player made.
4. Player refreshed Foundry. Changes made by the player were now updated correctly.
5. Triggered animation; **animation did not play.**
6. Triggered animation of spell that was previously verified to work; animation did not play.
7. Checked console; the following error appeared whenever triggering an animation:
![unknown](https://user-images.githubusercontent.com/66483265/150012519-30540842-0404-48a1-b113-304b4b620152.png)

8. Disabled and re-enabled AA. Checked animations again; did not play.
9. Forced an update on AA  - was using 1.2.5, forced an update which reinstalled 1.2.5. Checked animations again; did not play.
10. Uninstalled AA, then reinstalled and activated it. Checked animations again; **animations played as expected.** 

I will attempt to push further and test whether the issue is truly resolved, and will post an update if it persists or reappears. Nevertheless, this should be enough to reproduce the error. Please let me know if you need further info or details.

Cheers!

**Comment by otigon** [comment] 2022-01-18 21:02
Thanks for the report. The error that is listed should be fixed in version 1.2.5 (released) I'll run some troubleshooting as well to ensure the issue is resolved fully.

In the meantime you can update to 1.2.5

**Comment by Suracha-123** [comment] 2022-01-18 22:03
My bad, I forgot to mention that I was (and am) using 1.2.5. Edited the original to reflect this

**Comment by otigon** [comment] 2022-01-18 22:04
Ah gotcha, thanks again

**Comment by otigon** [comment] 2022-01-20 14:11
I wasn't able to replicate the error conditions outlined above. However, I did rearrange some items based on the error in hopes that the issue will not repeat itself. This is in version 1.2.6

If you run across the error again please let me know and I'll continue investigating

**Closed by otigon** 2022-01-20 14:11 UTC
