### ISSUE TITLE
[BUG] PF2e Rerolls use the initial result of the roll for the animation

### ISSUE THREAD

**Issue by MrVauxs** [otigon/automated-jb2a-animations#442] opened 2022-06-30 01:35 UTC
When rerolling an attack roll, the animation that is played again uses the first rolls result, rather than the new ones. This causes the animation to essentially always miss, regardless of the second result.

**Comment by Ghilteras** [comment] 2022-08-22 22:05
Does this work for 5e ADV/DISADV ? Seems very similar

**Comment by MrVauxs** [comment] 2022-08-22 23:14
> Does this work for 5e ADV/DISADV ? Seems very similar

I am not aware of 5e having a rerolling functionality baked into the rolls?

**Comment by MrVauxs** [comment] 2022-08-22 23:19
For reference.

https://user-images.githubusercontent.com/32039708/186036160-770475ce-fc50-4374-8528-0fd16a6abad2.mp4

**Comment by Ghilteras** [comment] 2022-08-22 23:39
This looks like ADV/DISADV in 5e so if it works there we can use the same logic for pf2e

**Comment by MrVauxs** [comment] 2022-08-23 01:02
You cannot right click to reroll a roll in 5e...

**Comment by Ghilteras** [comment] 2022-08-23 21:43
You don't understand what I'm saying. I'm asking whether this works in 5e because if it does than it means that the code that handle rerolls is already there and we would just have to change the trigger based on the system

**Comment by otigon** [comment] 2022-08-23 21:47
ADV/DADV is different from re-rolling. Advantage and Disadvantage are just single result outputs, whereas a reroll in PF2e is a completely separate roll

**Comment by MrVauxs** [comment] 2022-08-23 21:57
To explain further, advantage / disadvantage is a way of simultaneously rolling two of the same dice and picking the better or worse option. You cannot retroactively apply advantage or disadvantage.

What was being discussed here, is literally rolling the same thing again.

And PF2e has support for Advantage / Disadvantage. But again, not the actual topic, not relevant at all.

**Comment by otigon** [comment] 2022-10-24 22:38
Is this still an air after the System workflow rework in A-A?

**Comment by MrVauxs** [comment] 2022-10-24 23:05
Yes

**Comment by otigon** [comment] 2022-10-25 00:37
So I don't think this is any issue on my end. It just tested this (took a while to get a miss then hit.....) and the new Chat Message does not have the proper ``outcome`` flag in the chat message. For instance, I just rolled  and had a Critical Success, then chose to reroll and keep the worse result. The Flag did not change according to the new roll 
![image](https://user-images.githubusercontent.com/73318661/197655693-0efc5b1f-c4e7-45d1-b3d8-9e07ad808ba3.png)
![image](https://user-images.githubusercontent.com/73318661/197655711-aee29a39-b453-413f-8d95-2057935c20bf.png)

**Comment by MrVauxs** [comment] 2022-10-25 14:33
https://github.com/foundryvtt/pf2e/issues/4555

**Comment by otigon** [comment] 2022-10-26 13:12
Going to close this one out. With the current A-A workflow, if those Flags get updated on PF2e then everything should function as intended

**Closed by otigon** 2022-10-26 13:12 UTC
Labels: Feature Request
