### ISSUE TITLE
Issues with the new Aura animation options

### ISSUE THREAD

**Issue by Ssezra** [otigon/automated-jb2a-animations#32] opened 2021-04-12 22:27 UTC
Version 0.2.81
Just wanted to let you know that currently any Aura animation set as a radius of 30 or higher will not render. If the the aura radius is set to 25 or below it renders properly. 

Also the Aura opacity field is unable to be seen when set between 0-1. It appears as an empty box. (only when you highlight the empty field are you able to view entered data) 

Thanks for providing these new functions, It is appreciated.

**Comment by otigon** [comment] 2021-04-12 23:07
@Ssezra Thanks for letting me know. It looks like I left out the details for when the Radius is set to 30. I'll get that fixed on the next update

**Comment by Ssezra** [comment] 2021-04-20 02:49
Im just using the tidy sheet alternate (dark) theme. Entering data works its just not possible to see unless highlighted. I do notice that your opacity field remains black while other fields in different tabs are grey.
    On Monday, April 19, 2021, 09:54:52 PM EDT, otigon ***@***.***> wrote:  
 
 


Issues should be resolved for the 30 ft aura setting, as for the opacity setting, Are you using a custom sheet module? I can't replicate this issue

**Comment by otigon** [comment] 2021-04-21 22:31
@Ssezra I'm figuring out some CSS coloring for this, but I can confirm I'll at least have the text readable on the next release with the darkmode

**Comment by otigon** [comment] 2021-05-17 15:46
CSS should be implemented as of latest update to help out with Dark Mode issues.

**Closed by otigon** 2021-05-17 15:46 UTC
