### ISSUE TITLE
[BUG - 5e] Animate from ammunition no longer working

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#352] opened 2022-02-10 13:48 UTC
Hello,

FVTT 9.249
5e 1.5.7
AA 2.0.4

Let assume the following example:
- A longbow with a default animation
- This longbow use ammunition: "arrows" also with default animation
- If the option "Animate from Ammunition" is checked in the longbow configuration, no animation is played upon attack even tho the arrow ammunition exists

![image](https://user-images.githubusercontent.com/1687854/153420756-c8921c79-82dd-40cf-925a-5146b34c09b2.png)

![image](https://user-images.githubusercontent.com/1687854/153420816-815275fc-09c7-425f-a54c-fd34da19a31e.png)

**Comment by otigon** [comment] 2022-02-11 01:40
So this is a tricky one. The Automatic Recognition is being triggered off of the Longbow, and the ammunition is pointing back to the Automatic Recognition menu for any animation.

I'll have to do some more extensive reworks to get that to play correctly so I can't say when it will be fixed. For the meantime, you can define the animation on the Arrow item itself and it should work as intended. There is an error with this method that will be fixed on the next release

**Comment by DarKDinDoN** [comment] 2022-02-11 11:52
Ok, thx!

**Comment by otigon** [comment] 2022-02-21 21:05
feature will be left as-is, tying Ammunition animations into the Auto-rec would require more time than I'm willing to put into it. My work on this module is winding down to maintenance after the next few updates

**Closed by otigon** 2022-02-21 21:05 UTC
